apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4= # generated via - echo -n 'admin' | base64
  password: cGFzczEyMw== # generated via - echo -n 'pass123' | base64
  
  # Apply the YAML - kubectl apply -f my-secret.yaml