apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 3
  completions: 6
  template:
    spec:
      containers:
      - name: parallel-job
        image: busybox
        command: ["echo", "Task completed!"]
      restartPolicy: Never