apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: temp-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: temp-storage
    emptyDir: {}